name: Android CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
     

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 30
        build-tools: 30.0.3

    - name: Install Appium
      run: npm install -g appium

    - name: Start Appium server
      run: appium &

    - name: Build with Gradle
      run: ./gradlew build

    - name: Create Android emulator
      run: avdmanager create avd -n test -k "system-images;android-30;google_apis;x86_64"

    - name: Start emulator
      run: |
        emulator -avd test -no-window -no-audio &
        adb wait-for-device
        adb shell input keyevent 82

    - name: Run tests
      run: ./gradlew test

    - name: Archive test reports
      uses: actions/upload-artifact@v2
      with:
        name: test-reports
        path: build/reports/tests/test
