name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'corretto'
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 30
          build-tools: 30.0.3

      - name: Install Appium
        run: npm install -g appium

      - name: Start Appium server
        run: appium &

      - name: Create Android emulator
        run: avdmanager create avd -n test -k "system-images;android-30;google_apis;x86_64"

      - name: Start emulator
        run: |
          emulator -avd test -no-window -no-audio &
          adb wait-for-device
          adb shell input keyevent 82
          
          - name: Run tests
          run: ./gradlew test
          
          - name: Archive test reports
          uses: actions/upload-artifact@v2
          with:
          name: test-reports
          path: build/reports/tests/test

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
